export const FETCH_BILL_RESOURCES = 'FETCH_BILL_RESOURCES'
export const DO_SEARCH_BILL = 'DO_SEARCH_BILL'

export const FETCH_BILL_DROPDOWN = 'FETCH_BILL_DROPDOWN'
export const REMOVE_BILL_DROPDOWN = 'REMOVE_BILL_DROPDOWN'
export const DELETE_BILL_ACTION = 'DELETE_BILL_ACTION'
export const EDIT_BILL_ACTION = 'EDIT_BILL_ACTION'
export const CREATE_BILL_ACTION = 'CREATE_BILL_ACTION'
export const FETCH_BILL_DROPDOWN_SEARCH = 'FETCH_BILL_DROPDOWN_SEARCH'
