import { INVENTORY_VALUES } from '../common/app-constants'

export const INVENTORY = {
    INVENTORY_UNIT_TRANSPORT: 1,
    INVENTORY_UNIT_DELIVERY: 2,
    INVENTORY_USER: 3,
    INVENTORY_END: 4
}

export const INVENTORY_CONTENT = {
    [INVENTORY.INVENTORY_UNIT_TRANSPORT]: INVENTORY_VALUES[INVENTORY.INVENTORY_UNIT_TRANSPORT],
    [INVENTORY.INVENTORY_UNIT_DELIVERY]: INVENTORY_VALUES[INVENTORY.INVENTORY_UNIT_DELIVERY],
    [INVENTORY.INVENTORY_USER]: INVENTORY_VALUES[INVENTORY.INVENTORY_USER],
    [INVENTORY.INVENTORY_END]: INVENTORY_VALUES[INVENTORY.INVENTORY_END]
}

export const INVENTORY_SOURCE = [
    { code: INVENTORY.INVENTORY_UNIT_TRANSPORT, name: INVENTORY_VALUES[INVENTORY.INVENTORY_UNIT_TRANSPORT] },
    { code: INVENTORY.INVENTORY_UNIT_DELIVERY, name: INVENTORY_VALUES[INVENTORY.INVENTORY_UNIT_DELIVERY] },
    { code: INVENTORY.INVENTORY_USER, name: INVENTORY_VALUES[INVENTORY.INVENTORY_USER] },
    { code: INVENTORY.INVENTORY_END, name: INVENTORY_VALUES[INVENTORY.INVENTORY_END] }
]
