import AcceptCircleIcon from './AcceptCircle'
import AddPlusIcon from './AddPlus'
import AvatarIcon from './Avatar'
import BagBoldIcon from './BagBold'
import BookIcon from './Book'
import BookBoldIcon from './BookBold'
import CalendarIcon from './Calendar'
import CalendarBoldIcon from './CalendarBold'
import CancelIcon from './Cancel'
import CancelBoldIcon from './CancelBold'
import CartIcon from './Cart'
import CartBoldIcon from './CartBold'
import CartPlusIcon from './CartPlus'
import ChatIcon from './Chat'
import ChatBoldIcon from './ChatBold'
import ChatSquareIcon from './ChatSquare'
import ChatSquareBoldIcon from './ChatSquareBold'
import CheckIcon from './Check'
import ClipBoardIcon from './ClipBoard'
import CompanyIcon from './Company'
import CompanyBoldIcon from './CompanyBold'
import CreditCardIcon from './CreditCard'
import CrossIcon from './Cross'
import DeliveryIcon from './Delivery'
import DeliveryBoldIcon from './DeliveryBold'
import DownArrowIcon from './DownArrow'
import DownloadIcon from './Download'
import EditIcon from './Edit'
import EditBoldIcon from './EditBold'
import EmailIcon from './Email'
import EmailBoldIcon from './EmailBold'
import EyeIcon from './Eye'
import EyeHideIcon from './EyeHide'
import FaceBookIcon from './Facebook'
import FinanceIcon from './Finance'
import GarbageIcon from './Garbage'
import GarbageBoldIcon from './GarbageBold'
import GooglePlusIcon from './GooglePlus'
import HomeIcon from './Home'
import HomeBoldIcon from './HomeBold'
import InstagramIcon from './Instagram'
import LeftCircleIcon from './LeftCircle'
import LikeIcon from './Like'
import LikeBoldIcon from './LikeBold'
import LinkedInCircleIcon from './LinkedInCircle'
import ListIcon from './List'
import ListBoldIcon from './ListBold'
import LoginIcon from './Login'
import LoginBoldIcon from './LoginBold'
import LogoutIcon from './Logout'
import LogoutBoldIcon from './LogoutBold'
import MenuIcon from './Menu'
import MenuCircleIcon from './MenuCircle'
import MessengerCircleIcon from './MessengerCircle'
import MessengerIcon from './MessengerIcon'
import MinusIcon from './Minus'
import NextIcon from './Next'
import NotificationIcon from './Notification'
import PackageIcon from './Package'
import PasswordIcon from './PasswordIcon'
import PauseIcon from './Pause'
import PauseCircleIcon from './PauseCircle'
import PercentIcon from './Percent'
import PhoneCallIcon from './PhoneCall'
import PhoneDigitalIcon from './PhoneDigital'
import PictureBoldIcon from './PictureBold'
import PicturePlusIcon from './PicturePlus'
import PlaceholderIcon from './Placehoder'
import PlayIcon from './Play'
import PlusCircleIcon from './PlusCircle'
import PrevioustIcon from './Previous'
import PriceTagIcon from './Price'
import ProfileIcon from './Profile'
import ProvinceIcon from './Province'
import QuestionCircleIcon from './QuestionCircle'
import RegisterIcon from './Register'
import ReloadIcon from './Reload'
import RewindIcon from './Rewind'
import RightCircleIcon from './RightCircle'
import SearchIcon from './Search'
import SettingIcon from './Setting'
import ShopIcon from './Shop'
import ShopBoldIcon from './ShopBold'
import ShoppingBagIcon from './ShoppingBag'
import SkypeIcon from './Skype'
import StarIcon from './Star'
import TruckIcon from './Truck'
import TwitterIcon from './Twitter'
import UpArrowIcon from './UpArrow'
import UploadIcon from './Upload'
import UserCircleIcon from './UserCircle'
import UserProfileIcon from './UserProfile'
import UserProfileBoldIcon from './UserProfileBold'
import WarningIcon from './Warning'
import WebsiteIcon from './Website'
import YoutubeIcon from './YoutubeIcon'
import ZaloIcon from './ZaloIcon'

export { CheckIcon, ClipBoardIcon, CompanyIcon, CreditCardIcon, CrossIcon, DeliveryIcon, DownArrowIcon }
export { MenuCircleIcon, PictureBoldIcon, ShopBoldIcon, UserProfileBoldIcon, ProfileIcon, BookBoldIcon, PasswordIcon }
export { ChatSquareIcon, ChatBoldIcon, ChatSquareBoldIcon, CompanyBoldIcon, DeliveryBoldIcon, EditBoldIcon }
export { DownloadIcon, EditIcon, EmailIcon, EyeHideIcon, EyeIcon, FaceBookIcon, GarbageIcon, GooglePlusIcon }
export { UserCircleIcon, UserProfileIcon, WarningIcon, HomeIcon, QuestionCircleIcon, ChatIcon, CancelBoldIcon }
export { AcceptCircleIcon, AddPlusIcon, AvatarIcon, BookIcon, CalendarIcon, CancelIcon, CartIcon, CartPlusIcon }
export { PriceTagIcon, RegisterIcon, PlayIcon, ReloadIcon, RewindIcon, RightCircleIcon, SearchIcon, SettingIcon }
export { EmailBoldIcon, GarbageBoldIcon, HomeBoldIcon, LikeBoldIcon, ListBoldIcon, LoginBoldIcon, LogoutBoldIcon }
export { MinusIcon, MessengerCircleIcon, NotificationIcon, PauseCircleIcon, PauseIcon, PercentIcon, PhoneCallIcon }
export { ShopIcon, SkypeIcon, StarIcon, TwitterIcon, UpArrowIcon, UploadIcon, MenuIcon, InstagramIcon, CartBoldIcon }
export { LeftCircleIcon, LikeIcon, LinkedInCircleIcon, ListIcon, LoginIcon, LogoutIcon, ShoppingBagIcon, BagBoldIcon }
export { PhoneDigitalIcon, PicturePlusIcon, PlaceholderIcon, PlusCircleIcon, PrevioustIcon, NextIcon, CalendarBoldIcon }
export { ZaloIcon, YoutubeIcon, MessengerIcon, WebsiteIcon, TruckIcon, PackageIcon, ProvinceIcon, FinanceIcon }
